import type { EvaluateFirstPageTrustInput, FirstPageTrustAssessment } from './first-page-trust'

export interface LaunchGoldSetExpectation {
  expectedInvestorSignal: FirstPageTrustAssessment['investorSignal']
  expectedStatus: FirstPageTrustAssessment['status']
  suppressBreakevenSignal: boolean
  suppressForwardProjection: boolean
}

export interface LaunchGoldSetCase {
  address: string
  expectation: LaunchGoldSetExpectation
  input: EvaluateFirstPageTrustInput
  notes: string
  scenarioId: string
}

export const LAUNCH_GOLD_SET_CASES: readonly LaunchGoldSetCase[] = [
  {
    scenarioId: 'clean-sfr-primary-price',
    address: '8837 W Virginia Ave, Phoenix, AZ 85037',
    notes: 'Clean single-family rental with primary listing price and county tax record should remain trusted.',
    expectation: {
      expectedInvestorSignal: 'invest',
      expectedStatus: 'trusted',
      suppressBreakevenSignal: false,
      suppressForwardProjection: false,
    },
    input: {
      bathrooms: 2,
      bedrooms: 3,
      dataCompleteness: 'full',
      hoaSource: 'not-captured',
      insuranceSource: 'climate-model',
      listingPriceSource: 'primary',
      listingPriceStatus: 'resolved',
      monthlyNetCashFlow: 420,
      propertyTaxSource: 'county-record',
      propertyType: 'Single Family',
      rawScore: 91,
      sameBuildingRentCompCount: 0,
      squareFeet: 1552,
      totalRentCompCount: 5,
      valueConfidence: 'high',
      yearBuilt: 1986,
    },
  },
  {
    scenarioId: 'fallback-price-clean-sfr',
    address: '13801 N 36th Dr, Phoenix, AZ 85053',
    notes: 'Fallback listing price should keep the report usable but never fully trusted at launch.',
    expectation: {
      expectedInvestorSignal: 'think',
      expectedStatus: 'caution',
      suppressBreakevenSignal: false,
      suppressForwardProjection: false,
    },
    input: {
      bathrooms: 2,
      bedrooms: 3,
      dataCompleteness: 'full',
      hoaSource: 'not-captured',
      insuranceSource: 'climate-model',
      listingPriceSource: 'fallback',
      listingPriceStatus: 'resolved',
      monthlyNetCashFlow: 120,
      propertyTaxSource: 'county-record',
      propertyType: 'Single Family',
      rawScore: 72,
      sameBuildingRentCompCount: 0,
      squareFeet: 1850,
      totalRentCompCount: 4,
      valueConfidence: 'high',
      yearBuilt: 1971,
    },
  },
  {
    scenarioId: 'manual-conflict-price',
    address: '9812 S 11th Pl, Phoenix, AZ 85042',
    notes: 'Manually reconciled pricing should downgrade trust even when the rest of the page-one inputs are clean.',
    expectation: {
      expectedInvestorSignal: 'think',
      expectedStatus: 'caution',
      suppressBreakevenSignal: false,
      suppressForwardProjection: false,
    },
    input: {
      bathrooms: 2.5,
      bedrooms: 4,
      dataCompleteness: 'full',
      fallbackListingPrice: 439990,
      hoaSource: 'not-captured',
      insuranceSource: 'climate-model',
      listingPriceCheckedAt: '2026-04-16T12:00:00.000Z',
      listingPriceSource: 'user-confirmed',
      listingPriceStatus: 'resolved',
      listingPriceUserSupplied: true,
      monthlyNetCashFlow: 95,
      primaryListingPrice: 499990,
      propertyTaxSource: 'county-record',
      propertyType: 'Single Family',
      rawScore: 69,
      sameBuildingRentCompCount: 0,
      squareFeet: 1966,
      totalRentCompCount: 4,
      valueConfidence: 'high',
      yearBuilt: 2024,
    },
  },
  {
    scenarioId: 'stale-manual-price',
    address: '3000 Oasis Grand Blvd Apt 2502, Fort Myers, FL 33916',
    notes: 'A stale manual ask confirmation should never stay clean enough for page one.',
    expectation: {
      expectedInvestorSignal: 'run',
      expectedStatus: 'unsupported',
      suppressBreakevenSignal: true,
      suppressForwardProjection: true,
    },
    input: {
      bathrooms: 2,
      bedrooms: 2,
      dataCompleteness: 'full',
      hoaSource: 'listing',
      insuranceSource: 'hoa-adjusted-condo',
      listingPriceCheckedAt: '2026-04-14T12:00:00.000Z',
      listingPriceSource: 'user-confirmed',
      listingPriceStatus: 'resolved',
      listingPriceUserSupplied: true,
      monthlyNetCashFlow: -75,
      propertyTaxSource: 'county-record',
      propertyType: 'Condo',
      rawScore: 76,
      referenceTimeMs: Date.parse('2026-04-16T13:00:00.000Z'),
      sameBuildingRentCompCount: 2,
      squareFeet: 1319,
      totalRentCompCount: 4,
      valueConfidence: 'high',
      yearBuilt: 2008,
    },
  },
  {
    scenarioId: 'florida-condo-weak-rent-and-hoa',
    address: '3000 Oasis Grand Blvd Apt 2502, Fort Myers, FL 33916',
    notes: 'Florida condo with inferred HOA and weak rent support should be unsupported and suppress the headline metrics.',
    expectation: {
      expectedInvestorSignal: 'run',
      expectedStatus: 'unsupported',
      suppressBreakevenSignal: true,
      suppressForwardProjection: true,
    },
    input: {
      bathrooms: 2,
      bedrooms: 2,
      climateFloodInsuranceRequired: true,
      dataCompleteness: 'full',
      hoaSource: 'inferred-condo-default',
      insuranceSource: 'hoa-adjusted-condo',
      listingPriceSource: 'user-confirmed',
      listingPriceStatus: 'resolved',
      listingPriceUserSupplied: true,
      monthlyNetCashFlow: -125,
      propertyTaxSource: 'county-record',
      propertyType: 'Condo',
      rawScore: 82,
      rentWarnings: ['Rent estimate conflicts with nearby comps.'],
      reportWarnings: [
        {
          code: 'florida-condo-insurance-diligence',
          message: 'Insurance needs manual review.',
        },
      ],
      sameBuildingRentCompCount: 0,
      squareFeet: 1319,
      taxLikelyExempted: false,
      totalRentCompCount: 1,
      valueConfidence: 'low',
      yearBuilt: 2008,
    },
  },
  {
    scenarioId: 'building-avg-hoa-condo',
    address: '414 Water St Unit 1306, Baltimore, MD 21202',
    notes: 'Building-average HOA should keep a condo in caution, not trusted, while still allowing page-one metrics to render.',
    expectation: {
      expectedInvestorSignal: 'think',
      expectedStatus: 'caution',
      suppressBreakevenSignal: false,
      suppressForwardProjection: false,
    },
    input: {
      bathrooms: 2,
      bedrooms: 2,
      dataCompleteness: 'full',
      hoaSource: 'building-avg',
      insuranceSource: 'hoa-adjusted-condo',
      listingPriceSource: 'primary',
      listingPriceStatus: 'resolved',
      monthlyNetCashFlow: 85,
      propertyTaxSource: 'county-record',
      propertyType: 'Condo',
      rawScore: 70,
      sameBuildingRentCompCount: 1,
      squareFeet: 1280,
      totalRentCompCount: 4,
      valueConfidence: 'high',
      yearBuilt: 2008,
    },
  },
  {
    scenarioId: 'avm-only-property-facts',
    address: 'Generic AVM-only fallback case',
    notes: 'AVM-only property facts should never look like a clean investor-grade first page.',
    expectation: {
      expectedInvestorSignal: 'think',
      expectedStatus: 'unsupported',
      suppressBreakevenSignal: true,
      suppressForwardProjection: true,
    },
    input: {
      bathrooms: 2,
      bedrooms: 3,
      dataCompleteness: 'avm-only',
      hoaSource: 'not-captured',
      insuranceSource: 'climate-model',
      listingPriceSource: 'primary',
      listingPriceStatus: 'resolved',
      monthlyNetCashFlow: 140,
      propertyTaxSource: 'county-record',
      propertyType: 'Single Family',
      rawScore: 75,
      sameBuildingRentCompCount: 0,
      squareFeet: 1600,
      totalRentCompCount: 4,
      valueConfidence: 'medium',
      yearBuilt: 1998,
    },
  },
  {
    scenarioId: 'state-average-tax-and-fallback-insurance',
    address: 'Tax-default launch caution case',
    notes: 'State-average tax plus fallback-national insurance should stay in caution even when the rest of the property is clean.',
    expectation: {
      expectedInvestorSignal: 'think',
      expectedStatus: 'caution',
      suppressBreakevenSignal: false,
      suppressForwardProjection: false,
    },
    input: {
      bathrooms: 2,
      bedrooms: 3,
      dataCompleteness: 'full',
      hoaSource: 'not-captured',
      insuranceSource: 'fallback-national-average',
      listingPriceSource: 'primary',
      listingPriceStatus: 'resolved',
      monthlyNetCashFlow: 105,
      propertyTaxSource: 'state-average',
      propertyType: 'Single Family',
      rawScore: 67,
      sameBuildingRentCompCount: 0,
      squareFeet: 1710,
      totalRentCompCount: 4,
      valueConfidence: 'medium',
      yearBuilt: 1994,
    },
  },
]
