import Link from 'next/link'
import {
  ArrowLeftIcon,
  CalculatorIcon,
  DatabaseIcon,
  ShieldCheckIcon,
  UmbrellaIcon,
  ZapIcon,
  TargetIcon,
} from 'lucide-react'

export const metadata = {
  title: 'Methodology — How DealDoctor runs the numbers',
  description:
    'Transparent breakdown of every calculation and data source used in a DealDoctor report.',
}

import { prisma } from '@/lib/db'

// Server component so we can hit Prisma directly for the latest backtest run
// without spinning up another route / client fetch.
async function getLatestBacktest() {
  try {
    return await prisma.backtestRun.findFirst({
      orderBy: { runAt: 'desc' },
    })
  } catch {
    return null
  }
}

export default async function MethodologyPage() {
  const backtest = await getLatestBacktest()

  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:py-24">
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeftIcon className="h-4 w-4" />
        Back to DealDoctor
      </Link>

      <h1 className="mt-8 font-[family-name:var(--font-playfair)] text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
        Methodology
      </h1>
      <p className="mt-3 text-lg text-muted-foreground">
        Every number in your report comes from somewhere. Here&apos;s the full breakdown.
      </p>

      <Section icon={TargetIcon} title="Breakeven Offer Price">
        <p>
          The flagship metric. We binary-search the purchase price at which monthly
          cash flow is approximately $0, given today&apos;s 30-year fixed rate and the
          property&apos;s estimated rent.
        </p>
        <p>
          Assumptions: 20% down, 30-year amortization, 1.5% annual tax/insurance
          load on the purchase price, $250/mo operating buffer, 5% vacancy.
        </p>
        <p className="text-xs text-muted-foreground">
          Source code: <code>lib/calculations.ts#calculateBreakEvenPrice</code>
        </p>
      </Section>

      <Section icon={CalculatorIcon} title="Mortgage & Cash Flow">
        <p>
          Standard US mortgage amortization: monthly compounding,{' '}
          <code>P × (r × (1+r)^n) / ((1+r)^n − 1)</code>. The same formula your bank uses.
        </p>
        <p>
          Monthly net cash flow = gross rent × (1 − vacancy) − mortgage payment − expenses.
          Cash-on-cash return = annual net cash flow ÷ (down payment + rehab budget).
        </p>
      </Section>

      <Section icon={ShieldCheckIcon} title="DSCR (Debt Service Coverage Ratio)">
        <p>
          DSCR = annual NOI ÷ annual debt service. Most DSCR lenders require 1.25x or higher;
          some go to 1.0x with pricing adjustments. Below 1.0x = negative-cashflow deal.
        </p>
      </Section>

      <Section icon={UmbrellaIcon} title="Insurance & Climate Risk">
        <p>
          Insurance estimate uses NAIC state-level homeowners premium averages, scaled
          linearly by dwelling value. Flood-zone add-on applies when the property sits in
          a FEMA Special Flood Hazard Area.
        </p>
        <p>
          Flood zone is queried live from the FEMA National Flood Hazard Layer REST API
          using the property&apos;s geocoded coordinates.
        </p>
        <p>
          Climate hazard scores (hurricane, wildfire, heat, drought, tornado) are state-level
          heuristics — not address-level. Use them as a starting point, not a final
          insurance quote.
        </p>
        <p className="text-xs text-muted-foreground">
          Sources: NAIC Homeowners Insurance Report, FEMA NFHL, Mapbox geocoding.
        </p>
      </Section>

      <Section icon={DatabaseIcon} title="Rates & Market Data">
        <p>
          30-year and 15-year fixed rates are pulled from the Freddie Mac Primary Mortgage
          Market Survey, refreshed weekly. Fed funds rate from the FRED API.
        </p>
        <p>
          Property details (bedrooms, sqft, estimated value, year built) and rent estimates
          come from Rentcast. Sale comparables are filtered to same-bedroom-count properties
          within the same city.
        </p>
      </Section>

      <Section icon={ZapIcon} title="AI Deal Doctor">
        <p>
          The 3-fix diagnosis is generated by Anthropic. The AI never
          calculates numbers — all financial values (breakeven price, STR revenue estimate,
          70%-rule flip offer) are computed by our calculator and passed into the prompt.
          The model&apos;s job is narration and strategy ordering, not math.
        </p>
        <p>
          Photo red-flag review uses the same Anthropic model with vision input.
          Findings are observational only — the model is instructed not to speculate about
          anything not directly visible in frame.
        </p>
        <p>
          Fix 1 = lowest-effort path. Fix 2 = value-add or structural change. Fix 3 =
          strategic pivot.
        </p>
      </Section>

      <Section icon={ShieldCheckIcon} title="Accuracy — what we measure and publish">
        <p>
          We can&apos;t tell you any single report is correct — no AVM-based tool
          honestly can. What we can tell you:
        </p>
        <ol className="list-inside list-decimal space-y-1 pl-2">
          <li>The math is exact (131 automated tests).</li>
          <li>Every input is sourced and dated in the report footer.</li>
          <li>
            We flag divergence via our multi-source value triangulation — when
            estimates span more than 25%, confidence is marked low.
          </li>
          <li>
            We surface known-bad property patterns (student rentals, multi-unit
            zoning, yield outliers) before the paywall, not after.
          </li>
          <li>
            Every paid report links to Zillow, Redfin, and Realtor for the same
            address so you can cross-check in one click.
          </li>
        </ol>

        {backtest ? (
          <div className="mt-4 rounded-lg border bg-card p-4">
            <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted-foreground">
              Latest Accuracy Backtest
            </p>
            <p className="mt-1 text-sm text-foreground">
              Run {new Date(backtest.runAt).toLocaleDateString('en-US', {
                year: 'numeric', month: 'short', day: 'numeric',
              })}{' '}· sample of {backtest.sampleSize} reports
            </p>
            {backtest.valueWithin10 != null && (
              <p className="mt-1 text-sm text-foreground">
                <span className="font-semibold">
                  {(backtest.valueWithin10 * 100).toFixed(0)}%
                </span>{' '}
                of value predictions are within 10% of the current market AVM.
              </p>
            )}
            {backtest.valueMedianErr != null && (
              <p className="mt-0.5 text-sm text-muted-foreground">
                Median absolute value error: {(backtest.valueMedianErr * 100).toFixed(1)}%
              </p>
            )}
            {backtest.notes && (
              <p className="mt-2 text-[11px] text-muted-foreground">{backtest.notes}</p>
            )}
          </div>
        ) : (
          <div className="mt-4 rounded-lg border border-dashed bg-background/40 p-4">
            <p className="text-[11px] text-muted-foreground">
              Accuracy backtest results will publish here once we have enough
              historical reports to run a meaningful sample (target: quarterly
              after launch).
            </p>
          </div>
        )}
      </Section>

      <Section icon={ShieldCheckIcon} title="What DealDoctor is not">
        <p>
          Not financial advice. Not an appraisal. Not a substitute for a licensed inspection,
          a full underwriting review, or consultation with a qualified professional.
        </p>
        <p>
          Rent and value estimates have ranges of uncertainty inherent to any AVM. Before
          closing on a property, verify the numbers with a local agent, lender, or CPA.
        </p>
      </Section>

      <div className="mt-12 rounded-2xl border bg-card p-6 text-center">
        <h3 className="font-[family-name:var(--font-playfair)] text-xl font-bold text-foreground">
          Still have questions?
        </h3>
        <p className="mt-1 text-sm text-muted-foreground">
          The report is a starting point for diligence, not the end of it. If something
          looks off, email us — we&apos;ll walk through the numbers with you.
        </p>
      </div>
    </div>
  )
}

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>
  title: string
  children: React.ReactNode
}) {
  return (
    <section className="mt-10 rounded-xl border bg-card p-6 sm:p-8">
      <div className="mb-3 flex items-center gap-2">
        <Icon className="h-5 w-5 text-primary" />
        <h2 className="font-[family-name:var(--font-playfair)] text-xl font-bold text-foreground">
          {title}
        </h2>
      </div>
      <div className="space-y-3 text-sm leading-relaxed text-muted-foreground [&>p>code]:rounded [&>p>code]:bg-muted [&>p>code]:px-1.5 [&>p>code]:py-0.5 [&>p>code]:text-foreground">
        {children}
      </div>
    </section>
  )
}
